version: '3.8'
services:
 jenkins:
   image: danielgomeza/jenkins-model-template:v3
   privileged: true
   user: root
   ports:
    - 8181:8080
    - 50000:50000
   container_name: jenkins-model-template-container
   volumes:
    - $HOME/jenkins-volumes/jenkins-model-template-v2:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock