version: '3.8'
services:
 jenkins:
   image: danielgomeza/jenkins-docker-compose-customized:latest
   privileged: true
   user: root
   ports:
    - 8080:8080
    - 50000:50000
   container_name: jenkins-docker-compose-customized-container
   volumes:
    - $HOME/jenkins-volumes/jenkins-docker-compose-customized:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock